### ISSUE TITLE
How to test with ExpectFind()?

### ISSUE THREAD

**Issue by dtelyukh** [go-kivik/kivikmock#66]
```
	client, mock, err := kivikmock.New()
	if err != nil {
		t.Fatal(err)
	}

	db := mock.NewDB()
	mock.ExpectDB().WithName("somedbname").WillReturn(db)
	db.ExpectFind().WillReturn(kivikmock.NewRows().AddRow(<what's here?>))
```

**Comment by flimzy** [comment]
I'm sorry for the long delay in replying.

You need to provide a [*driver.Row](https://pkg.go.dev/github.com/go-kivik/kivik/v3/driver?tab=doc#Row) value there, as you can see from [the function signature](https://pkg.go.dev/github.com/go-kivik/kivikmock/v3?tab=doc#Rows.AddRow). Example:

```
db.ExpectFind().WillReturn(kivikmock.NewRows().AddRow(&driver.Row{
    ID: "foo",
}))
`
